config/routes.rb
UkPostcodes::Application.routes.draw do
  root :to => 'postcode#index'

  get "postcode/search", as: "postcode_search", to: 'postcode#search'
  get "postcode/nearest", as: "postcode_nearest", to: 'postcode#nearest'
  get "distance.php", as: "postcode_nearest", to: 'postcode#nearest'
  get "postcode/reverse", as: "postcode_reverse", to: 'postcode#reverse'

  resources :postcode, :only => [:index, :show]
  
  get "latlng/:latlng", to: 'postcode#reverse', as: "latlng", :constraints => { :latlng => /[^\/]+(?=\.html\z|\.json\z|\.csv\z|\.rdf\z)|[^\/]+/ }
    
  get ":page", to: 'application#static'
    
end

app/models/postcode.rb
class Postcode < ActiveRecord::Base
  
  self.rgeo_factory_generator = RGeo::Geos.factory_generator

  set_rgeo_factory_for_column(:latlng, RGeo::Geographic.spherical_factory(:srid => 4326))
  
  ADMIN_AREAS = [:council, :county, :ward, :constituency, :parish, :electoral_district]
  
  def lat
    self.latlng.x
  end
  
  def lng
    self.latlng.y
  end
  
  def easting
    self.eastingnorthing.x
  end
  
  def northing
    self.eastingnorthing.y
  end
  
  def distance_from(lat, lng)
    d = Geodesic::dist_haversine(self.lat, self.lng, lat, lng)
    (d * 0.6214).round(4)
  end
  
  def admin_areas
    areas = {}
    ADMIN_AREAS.each do |area|
      areas[area] = self.send("#{area}_details")
    end
    areas.delete_if {|k,v| v.blank?}
  end
  
  def geohash
    hash = GeoHash.encode(self.lat, self.lng)
    "http://geohash.org/#{hash}"
  end
  
  def method_missing(method_name, *args, &blk)
    val = method_name.to_s.match(/(.+)_details/)
    unless val.nil?
      c = Code.where(:gss => self.send(val[1])).first
      area_details(c)
    else
      super
    end
  end
  
  def electoral_district_details
    unless ni?
      b = Boundary.where("kind = 'CountyElectoralDivision' AND ST_Contains(shape, ST_Geomfromtext('POINT(#{self.easting} #{self.northing})'))").first
      area_details(b)
    end
  end

  def parish_details
    unless ni?
      b = Boundary.where("kind = 'CivilParish' AND ST_Contains(shape, ST_Geomfromtext('POINT(#{self.easting} #{self.northing})'))").first
      area_details(b)
    end
  end
  
  def area_details(area)
    unless area.nil?
      {
        :name => area.name,
        :gss => area.gss,
        :os => area.os,
        :ons_uri => "http://statistics.data.gov.uk/id/statistical-geography/#{area.gss}",
        :os_uri => "http://data.ordnancesurvey.co.uk/id/#{area.os}",
        :kind => area.kind
      }
    else
      {}
    end
  end
  
  def to_csv
    CSV.generate do |csv|
      csv << [
          self.postcode,
          self.lat,
          self.lng,
          self.easting,
          self.northing,
          geohash,
          county_details[:gss],
          county_details[:name],
          council_details[:gss],
          council_details[:name],
          ward_details[:gss],
          ward_details[:name]
        ]
    end
  end
  
  def ni?
    country == "N92000002"
  end
  
end

app/controllers/postcode_controller.rb
class PostcodeController < ApplicationController
  include PostcodeHelper
  
  caches_page :index, :show
  
  before_filter(:only => [:show, :nearest]) { alternate_formats [:json, :xml, :rdf, :csv, :n3] }

  def index
    
  end
  
  def show
    if params[:id].match(/\s/) || params[:id].match(/[a-z]/)
      postcode = params[:id].gsub(' ', '').upcase
      params[:format] ||= "html"
      redirect_to postcode_url(postcode, format: params[:format]), status: "301"
      return
    end
    
    if params[:callback] && params[:format] == 'json' && !request.original_fullpath.match(/jsonp/)
      params[:format] = "jsonp"
      redirect_to postcode_url(params[:id], params), status: "301" and return 
    end
        
    p = UKPostcode.new(params[:id])
    postcode = p.norm
    
    render_error(404, "Postcode #{p.to_s} is not valid") and return unless p.valid?
    
    @postcode = Postcode.where(:postcode => postcode).first
    
    if postcode == "" || @postcode.nil?
      render_error(404, "Postcode #{p.to_s} cannot be found")
      return
    else    
      respond_to do |format|
        format.html
        format.json
        format.xml
        format.rdf { show_rdf(@postcode, :rdfxml) }
        format.n3 { show_rdf(@postcode, :ntriples) }
        format.csv { render :text => @postcode.to_csv }
      end
    end
  end
  
  def nearest
    if params[:postcode]
      p = UKPostcode.new(params[:postcode])
      postcode = Postcode.where(:postcode => p.norm).first
      params[:lat] = postcode.lat
      params[:lng] = postcode.lng
      @postcode = postcode.postcode
    else
      render_error(422, "You must specify a latitude and longitude") and return if params[:lat].blank? || params[:lng].blank?
      @postcode = nil
    end
    
    @lat = params[:lat].to_f
    @lng = params[:lng].to_f
    
    params[:miles] ||= params[:distance]
    
    render_error(422, "You must specify a distance") and return if params[:miles].blank?    
    render_error(422, "The maximum radius is 5 miles") and return if params[:miles].to_i > 5
        
    distance = params[:miles].to_f * 1609.344
    
    @postcodes = Postcode.where("ST_DWithin(latlng, ST_Geomfromtext('POINT(#{@lat} #{@lng})'), #{distance})").
                                order("ST_Distance(latlng, ST_Geomfromtext('POINT(#{@lat} #{@lng})'))")
        
    respond_to do |format|
      format.html
      format.json
      format.xml
      format.rdf { nearest_rdf(@postcodes, :rdfxml) }
      format.n3 { nearest_rdf(@postcode, :ntriples) }
      format.csv do
        csv = []
        @postcodes.each do |postcode|
          csv << postcode.to_csv
        end
        render :text => csv.join()
      end
    end
  end
  
  def reverse
    if params[:latlng]
      latlng = params[:latlng].split(",")
      if params[:latlng] =~ /\.html|\.xml|\.json|\.rdf/
        params[:format] = params[:latlng].split(".").last
      end
      params[:lat] = latlng[0]
      params[:lng] = latlng[1]
    end
    
    if params[:lat].blank? || params[:lng].blank?
      render_error(422, "You must specify a latitude and longitude") and return
    end
    
    params[:format] ||= "html"
    
    postcodes = Postcode.where("ST_DWithin(latlng, 'POINT(#{params[:lat].to_f} #{params[:lng].to_f})', 1609.344)")
                              .order("ST_Distance(latlng, 'POINT(#{params[:lat].to_f} #{params[:lng].to_f})')")
                                  
    if postcodes.count == 0
      render_error(404, "No postcode found for #{params[:lat]},#{params[:lng]}")
      return
    else
      postcode = postcodes.first
      p = postcode.postcode.gsub(" ", "")
      redirect_to postcode_url(p, format: params[:format]), status: "303"
    end
  end
  
  def search
    p = UKPostcode.new(params[:q])
    
    render_error(404, "Postcode #{p.to_s} is not valid") and return unless p.valid?
    
    postcode = p.norm.gsub(" ", "")    
    redirect_to postcode_url(postcode, format: params[:format]), status: "303"
  end

end

app/helpers/postcode_helper.rb
module PostcodeHelper
  
  def prefixes
    {
      :geo              => RDF::Vocabulary.new("http://www.w3.org/2003/01/geo/wgs84_pos#"),
      :spatialrelations => RDF::Vocabulary.new("http://data.ordnancesurvey.co.uk/ontology/spatialrelations/"),
      :admingeo         => RDF::Vocabulary.new("http://statistics.data.gov.uk/def/administrative-geography/"),
      :elecgeo          => RDF::Vocabulary.new("http://statistics.data.gov.uk/def/electoral-geography/"),
      :osadmingeo       => RDF::Vocabulary.new("http://data.ordnancesurvey.co.uk/ontology/admingeo/"),
      :owl              => RDF::Vocabulary.new("http://www.w3.org/2002/07/owl#"),
      :rdfs             => RDF::Vocabulary.new("http://www.w3.org/2000/01/rdf-schema#")
    }
  end
  
  def show_rdf(postcode, format)
    graph = RDF::Graph.new
    
    p = RDF::URI.new("http://uk-postcodes.com/postcode/#{postcode.postcode.gsub(" ", "")}")
    
    graph << [p, prefixes[:rdfs].label, postcode.postcode]
    graph << [p, RDF.type, RDF::URI.new("http://data.ordnancesurvey.co.uk/ontology/postcode/PostcodeUnit")]
    
    unless postcode.ni?
      graph << [p, prefixes[:owl].sameAs, RDF::URI.new("http://data.ordnancesurvey.co.uk/id/postcodeunit/#{postcode.postcode.gsub(" ", "")}")]
    end
    
    graph << [p, prefixes[:geo].lat, RDF::Literal.new(postcode.lat, :datatype => RDF::XSD.decimal) ]
    graph << [p, prefixes[:geo].long, RDF::Literal.new(postcode.lng, :datatype => RDF::XSD.decimal) ]
    graph << [p, prefixes[:spatialrelations].easting, postcode.easting.to_int ]
    graph << [p, prefixes[:spatialrelations].northing, postcode.northing.to_int ]
    
    unless postcode.ni?
      postcode.admin_areas.each do |title, area|
        unless area[:gss] == "999999999"
          graph << [p, prefixes[:spatialrelations]['t_spatiallyInside'], RDF::URI.new(area[:ons_uri]) ]
        end
        os_uri = RDF::URI.new(area[:os_uri])
        graph << [p, prefixes[:osadmingeo][area[:kind]], os_uri ]
        graph << [os_uri, prefixes[:rdfs].label, area[:name]]
      end
    end
    
    render :text => graph.dump(format, :prefixes => prefixes)  
  end
  
  def nearest_rdf(postcodes, format)
    graph = RDF::Graph.new
    
    postcodes.each do |postcode|
      p = RDF::URI.new("http://uk-postcodes.com/postcode/#{postcode.postcode.gsub(" ", "")}")
      
      graph << [p, prefixes[:rdfs].label, postcode.postcode]
      graph << [p, RDF.type, RDF::URI.new("http://data.ordnancesurvey.co.uk/ontology/postcode/PostcodeUnit")]
      
      unless postcode.ni?
        graph << [p, prefixes[:owl].sameAs, RDF::URI.new("http://data.ordnancesurvey.co.uk/id/postcodeunit/#{postcode.postcode.gsub(" ", "")}")]
      end
      
      graph << [p, prefixes[:geo].lat, RDF::Literal.new(postcode.lat, :datatype => RDF::XSD.decimal) ]
      graph << [p, prefixes[:geo].long, RDF::Literal.new(postcode.lng, :datatype => RDF::XSD.decimal) ]
      graph << [p, prefixes[:spatialrelations].easting, postcode.easting.to_int ]
      graph << [p, prefixes[:spatialrelations].northing, postcode.northing.to_int ]
    end
    
    render :text => graph.dump(format, :prefixes => prefixes)
  end
  
end

app/views/postcode/index.html.erb
<div class="row">
  <h1>UK Postcodes</h1>
  
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <ul class="nav nav-tabs">
        <li class="active"><a href="#postcode" data-toggle="tab">Postcode</a></li>
        <li><a href="#nearest" data-toggle="tab">Nearest</a></li>
        <li><a href="#reverse" data-toggle="tab">Reverse</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="postcode">
          <%= form_tag("/postcode/search", method: "get", role: "form", class: "form-inline") do %>
            <div class="form-group">
              <label>Give me data for <%= text_field_tag(:q, nil, {:placeholder => "Postcode", :class => "form-control"}) %></label>
            </div>
            <div class="form-group">
              <label>in <%= select_tag :format, options_for_select(["html", "json", "xml", "csv", "rdf"]), :class => "form-control" %> format</label>
            </div>
            <div class="form-group">
              <%= button_tag("please", :class => "btn", :type => "submit") %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane" id="nearest">
          <%= form_tag("/postcode/nearest", method: "get", role: "form", class: "form-inline") do %>
            <div class="form-group">
              <label>Show me postcodes within <%= text_field_tag(:miles, nil, {:class => "form-control"}) %> miles</label>
            </div>
            <div class="form-group">
              <label>of <%= text_field_tag(:postcode, nil, {:placeholder => "Postcode", :class => "form-control"}) %> </label> 
            </div>
            <div class="form-group">
              in <%= select_tag :format, options_for_select(["html", "json", "xml", "csv", "rdf"]), :class => "form-control" %> format
            </div>
            <div class="form-group">
              <%= button_tag("please", :class => "btn", :type => "submit") %>
            </div>
          <% end %>
        </div>
        <div class="tab-pane" id="reverse">
          <%= form_tag("/postcode/reverse", method: "get", role: "form", class: "form-inline") do %>
          <div class="form-group">
            Give me data for the nearest postcode to
            <%= label_tag('lat', 'Latitude', {:class => 'text-hide'})%>
            <%= text_field_tag(:lat, nil, {:placeholder => "Latitude", :class => "form-control"}) %>,
          </div>
          <div class="form-group">
            <%= label_tag('lng', 'Longitude', {:class => 'text-hide'})%>
            <%= text_field_tag(:lng, nil, {:placeholder => "Longitude", :class => "form-control"}) %>
          </div>
          <div class="form-group">
            in <%= select_tag :format, options_for_select(["html", "json", "xml", "csv", "rdf"]), :class => "form-control" %> format
          </div>
          <div class="form-group">
            <%= submit_tag("please", :class => "btn") %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/postcode/nearest.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Postcodes within <%= params[:miles] %> miles of <%= @postcode || "#{@lat}, #{@lng}" %></h1>

    <ul>
      <% @postcodes.each do |postcode| %>
        <li><%= link_to postcode.postcode, postcode_path(postcode.postcode.gsub(" ", "")) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <p class="text-center">Get this data as:</p>
    <p class="text-center"><%= alternate_link_buttons(:icon => '') %></p>
  </div>
</div>

app/views/postcode/show.html.erb
<div class="vcard">
  <div class="adr">
  <h1>Data for <span class="fn org postal-code"><%= @postcode.postcode %></span></h1>
    <div class="result geo row">
      <div class="col-md-7">
      <dl class="dl-horizontal">
        <dt>Latitude</dt>
        <dd class="latitude"><%= @postcode.lat.round(6) %></dd>
        <dt>Longitude</dt>
        <dd class="longitude"><%= @postcode.lng.round(6) %></dd>
        <dt>Easting</dt>
        <dd class="easting"><%= @postcode.easting.to_i %> <%= "<em class='ing'>(Irish National Grid)</em>".html_safe if @postcode.ni? %></dd>
        <dt>Northing</dt>
        <dd class="northing"><%= @postcode.northing.to_i %> <%= "<em class='ing'>(Irish National Grid)</em>".html_safe if @postcode.ni? %></dd>
        <dt>Geohash URI</dt>
        <dd class="geohash_uri"><%= link_to @postcode.geohash, @postcode.geohash %></dd>
        <dt>Openly Local URL</dt>
        <dd class="openly_local_url"><%= link_to "http://openlylocal.com/areas/postcodes/#{@postcode.postcode.gsub(' ', '')}", "http://openlylocal.com/areas/postcodes/#{@postcode.postcode.gsub(' ', '')}" %></dd>          
        <% @postcode.admin_areas.each do |title, area| %>
            <dt><%= title.to_s.titleize %></dt> 
            <% if @postcode.ni? %>
              <dd class="<%= title.to_s.gsub(" ", "_") %>"><%= area[:name] %></dd>
            <% else %>
              <dd class="<%= title.to_s.gsub(" ", "_") %>"><%= link_to area[:name], area[:os_uri] %></dd>
            <% end %>
        <% end %>
      </dl>
      </div>
      <div class="col-md-5">
        <%= map(:center => {
            :latlng => [@postcode.lat, @postcode.lng],
            :zoom => 16,
            },
            :markers => [
              {
                 :latlng => [@postcode.lat, @postcode.lng],
              }
            ]
        )%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="text-center">Get this data as:</p>
        <p class="text-center"><%= alternate_link_buttons(:icon => '') %></p>
      </div>
    </div>
  </div>
</div>